language: ru
languages:
  - label: Русский
    flag: ru
    code: ru
  - label: English
    flag: en
    code: en

assets: "**/*.svg"

redirects:
  - from: subfolder/test2
    to: /test2
  - from: subfolder/test3
    to: /test3
  - from: subfolder/tables/multiline
    to: /index
  - from: subfolder/tables/gfm
    to: /index